### ISSUE TITLE
Explictly condemn turning frustration into personal attack

### ISSUE THREAD

**Issue by zbraniecki** [tkellen/tc39-code-of-conduct-proposal#10]
Mozilla CPG uses the following wording:

```
Be respectful. We may not always agree, but disagreement is no excuse for poor manners. We will all experience some frustration now and then, but we don’t allow that frustration to turn into a personal attack.
```

I don't know if we need the whole phrase, but I'd like to see that expressed explicitly since the dynamic in the committee is very affected by this dynamic.

**Comment by bterlson** [comment]
I am already seeing this text...

**Comment by zbraniecki** [comment]
I don't know why I didn't see it on the first read. Closing.
